# Generated by Django 5.1.4 on 2024-12-15 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_category_parent_id_category_category_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='id_variant',
        ),
        migrations.AddField(
            model_name='productimage',
            name='id_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.product'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='status',
            field=models.IntegerField(choices=[(0, 'out of stockstock'), (1, 'in stock')], default=1),
        ),
    ]
